### ISSUE TITLE
The Facebook friends doesn't load

### ISSUE THREAD

**Issue by harvir** [relatedcode/ParseChat#4]
If I want to start a chat by selecting a facebook friend it is just blank.

<img width="308" alt="screen shot 2016-01-01 at 23 52 28" src="https://cloud.githubusercontent.com/assets/9304636/12072652/df8e144e-b0e2-11e5-9eff-332e97fe824e.png">

Help is much appreciated.

**Comment by Xenero** [comment]
You have to have other facebook friends using the application AS WELL AS be signed in using facebook.

Also, try updating all your SDK's as they have released a few bug fixes recently to work with the new Parse structure.
